import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { AndroidApplicationGeneratedModule, AndroidApplicationGeneratedSharedModule } from './generated/module';
import { AndroidApplicationValidator, registerValidationChecks } from './android-application-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AndroidApplicationAddedServices = {
    validation: {
        AndroidApplicationValidator: AndroidApplicationValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AndroidApplicationServices = LangiumServices & AndroidApplicationAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AndroidApplicationModule: Module<AndroidApplicationServices, PartialLangiumServices & AndroidApplicationAddedServices> = {
    validation: {
        AndroidApplicationValidator: () => new AndroidApplicationValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAndroidApplicationServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    AndroidApplication: AndroidApplicationServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AndroidApplicationGeneratedSharedModule
    );
    const AndroidApplication = inject(
        createDefaultModule({ shared }),
        AndroidApplicationGeneratedModule,
        AndroidApplicationModule
    );
    shared.ServiceRegistry.register(AndroidApplication);
    registerValidationChecks(AndroidApplication);
    return { shared, AndroidApplication };
}
